apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: html5demos
  namespace: argocd
spec:
  project: default
  source:
    repoURL: http://linux03.local:3000/admin/html5demos-chart.git
    targetRevision: main
    path: .
    helm:
      postRenderer:
        exec:
          command: ["kustomize", "build", "overlays/sidecar"]
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated: {}
