apiVersion: apps/v1
kind: Deployment
metadata:
  name: html5demos
spec:
  template:
    spec:
      containers:
        - name: nginx-exporter
          image: nginx/nginx-prometheus-exporter:0.13.0
          args:
            - -nginx.scrape-uri=http://localhost:80/stub_status
          ports:
            - containerPort: 9113
              name: metrics
